import {
  Briefcase,
  Star,
  GraduationCap,
  Sparkles,
  Compass,
  Bell,
  Users,
  BarChart3,
  BookOpen,
  HelpCircle,
  Layers,
  Code2,
  Cpu,
  MapPin,
  Building,
} from "lucide-react";

export const CATEGORIES = [
  "All",
  "Career Journey",
  "Interview Preparation",
  "Internship",
  "Placement Journey",
  "Career Advice",
  "Technical Article",
  "Guide & Tutorial",
  "Project Experience",
  "Architecture & System",
  "Job Opportunity",
  "Alumni Achievement",
  "Mentorship",
  "Industry Insights",
  "Workplace Experience",
  "Announcement",
  "Technical Roadmap",
];

export const categoryStyles = {
  "Technical Roadmap": {
    bg: "#ecfdf5",
    color: "#047857",
    border: "#a7f3d0",
    gradient: "linear-gradient(135deg, #10b981, #059669)",
    icon: Compass,
  },
  "Guide & Tutorial": {
    bg: "#eff6ff",
    color: "#1d4ed8",
    border: "#bfdbfe",
    gradient: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    icon: BookOpen,
  },
  "Interview Preparation": {
    bg: "#fef3c7",
    color: "#b45309",
    border: "#fde68a",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    icon: HelpCircle,
  },
  "Architecture & System": {
    bg: "#f5f3ff",
    color: "#7c3aed",
    border: "#ddd6fe",
    gradient: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    icon: Layers,
  },
  "Project Experience": {
    bg: "#fff7ed",
    color: "#c2410c",
    border: "#fed7aa",
    gradient: "linear-gradient(135deg, #ea580c, #c2410c)",
    icon: Code2,
  },
  "Technical Article": {
    bg: "#eff6ff",
    color: "#1d4ed8",
    border: "#bfdbfe",
    gradient: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    icon: BookOpen,
  },
  "Interview Experience": {
    bg: "#fef3c7",
    color: "#b45309",
    border: "#fde68a",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    icon: HelpCircle,
  },
  "Career Advice": {
    bg: "#dbeafe",
    color: "#1d4ed8",
    border: "#93c5fd",
    gradient: "linear-gradient(135deg, #2563eb, #1d4ed8)",
    icon: Compass,
  },
  "Job Opportunity": {
    bg: "#d1fae5",
    color: "#047857",
    border: "#6ee7b7",
    gradient: "linear-gradient(135deg, #10b981, #059669)",
    icon: Briefcase,
  },
  "Internship": {
    bg: "#f3e8ff",
    color: "#7e22ce",
    border: "#d8b4fe",
    gradient: "linear-gradient(135deg, #8b5cf6, #7c3aed)",
    icon: GraduationCap,
  },
  "Alumni Achievement": {
    bg: "#fef3c7",
    color: "#b45309",
    border: "#fcd34d",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    icon: Star,
  },
  "Career Journey": {
    bg: "#e0f2fe",
    color: "#0369a1",
    border: "#7dd3fc",
    gradient: "linear-gradient(135deg, #0284c7, #0369a1)",
    icon: Compass,
  },
  "Announcement": {
    bg: "#ffedd5",
    color: "#c2410c",
    border: "#fdba74",
    gradient: "linear-gradient(135deg, #f97316, #ea580c)",
    icon: Bell,
  },
  "Mentorship": {
    bg: "#ccfbf1",
    color: "#0f766e",
    border: "#99f6e4",
    gradient: "linear-gradient(135deg, #14b8a6, #0d9488)",
    icon: Users,
  },
  "Industry Insights": {
    bg: "#e0e7ff",
    color: "#4338ca",
    border: "#a5b4fc",
    gradient: "linear-gradient(135deg, #6366f1, #4f46e5)",
    icon: BarChart3,
  },
  "Placement Journey": {
    bg: "#fef3c7",
    color: "#b45309",
    border: "#fde68a",
    gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
    icon: GraduationCap,
  },
  "Workplace Experience": {
    bg: "#f0fdf4",
    color: "#15803d",
    border: "#bbf7d0",
    gradient: "linear-gradient(135deg, #22c55e, #16a34a)",
    icon: Building,
  },
};

export const getCategoryStyle = (categoryName) => {
  return (
    categoryStyles[categoryName] || {
      bg: "#f1f5f9",
      color: "#475569",
      border: "#cbd5e1",
      gradient: "linear-gradient(135deg, #64748b, #475569)",
      icon: BookOpen,
    }
  );
};
