import {
  Layers,
  Code2,
  Server,
  Palette,
  Coffee,
  Terminal,
  Brain,
  Sparkles,
  BarChart3,
  Binary,
  Cloud,
  GitBranch,
  ShieldCheck,
  Database,
  Smartphone,
  Network,
  Cpu,
  GitPullRequest,
} from "lucide-react";

export const DOMAINS = [
  {
    id: "mern-stack",
    name: "MERN Stack",
    stack: "MongoDB • Express • React • Node.js",
    icon: Layers,
    description: "Full-stack web applications, REST APIs, JWT authentication, deployment, and modern web application architecture.",
    accentColor: "#2563eb",
    bgColor: "#eff6ff",
    borderColor: "#bfdbfe",
    tag: "Full Stack",
    keywords: ["mern", "react", "node", "mongodb", "express", "fullstack", "full stack"],
  },
  {
    id: "frontend-development",
    name: "Frontend Development",
    stack: "HTML • CSS • JavaScript • React • UI",
    icon: Code2,
    description: "Responsive interfaces, component architecture, state management, modern CSS, and web performance optimization.",
    accentColor: "#4f46e5",
    bgColor: "#eef2ff",
    borderColor: "#c7d2fe",
    tag: "Frontend & Web",
    keywords: ["frontend", "javascript", "react", "html", "css", "tailwind", "responsive"],
  },
  {
    id: "backend-development",
    name: "Backend Development",
    stack: "Node.js • Express • APIs • Databases",
    icon: Server,
    description: "Server architectures, RESTful API design, database modeling, authentication services, and microservices.",
    accentColor: "#0d9488",
    bgColor: "#f0fdfa",
    borderColor: "#99f6e4",
    tag: "Backend & APIs",
    keywords: ["backend", "node", "express", "api", "rest api", "databases", "microservices"],
  },
  {
    id: "ui-ux-design",
    name: "UI/UX & Figma",
    stack: "Figma • Wireframes • Prototyping • Design Systems",
    icon: Palette,
    description: "User research, wireframing, interactive prototyping, Figma design systems, and usability principles.",
    feedDescription: "Explore Figma design systems, wireframing, interactive prototyping, and usability principles.",
    accentColor: "#9333ea",
    bgColor: "#faf5ff",
    borderColor: "#e9d5ff",
    tag: "Design & UX",
    keywords: ["ui", "ux", "figma", "wireframes", "prototyping", "design systems", "design"],
    aliases: ["UI/UX & Figma", "UI/UX Design", "Figma & Design", "UI/UX", "Figma"],
  },
  {
    id: "java-development",
    name: "Java Development",
    stack: "Java • OOP • Collections • Spring Boot",
    icon: Coffee,
    description: "Enterprise backend engineering, object-oriented programming, Spring Boot microservices, and JVM internals.",
    accentColor: "#d97706",
    bgColor: "#fffbeb",
    borderColor: "#fde68a",
    tag: "Enterprise Java",
    keywords: ["java", "spring", "spring boot", "oop", "collections", "hibernate"],
  },
  {
    id: "python-development",
    name: "Python Development",
    stack: "Python • Automation • Backend • Scripting",
    icon: Terminal,
    description: "High-performance APIs, automation scripts, backend services, web scraping, and Python development patterns.",
    accentColor: "#0284c7",
    bgColor: "#f0f9ff",
    borderColor: "#bae6fd",
    tag: "Python & APIs",
    keywords: ["python", "django", "fastapi", "automation", "scripting", "flask"],
  },
  {
    id: "ai-ml",
    name: "AI & Machine Learning",
    stack: "ML • Deep Learning • NLP • Model Dev",
    icon: Brain,
    description: "Machine learning algorithms, deep neural networks, computer vision, natural language processing, and evaluation.",
    accentColor: "#7c3aed",
    bgColor: "#f5f3ff",
    borderColor: "#ddd6fe",
    tag: "AI & Learning",
    keywords: ["ai", "machine learning", "deep learning", "nlp", "ml", "pytorch", "neural networks"],
  },
  {
    id: "generative-ai",
    name: "Generative AI",
    stack: "LLMs • Prompt Eng • RAG • AI Apps",
    icon: Sparkles,
    description: "Large language models, prompt engineering, Retrieval-Augmented Generation (RAG), and production AI agents.",
    accentColor: "#a855f7",
    bgColor: "#faf5ff",
    borderColor: "#f3e8ff",
    tag: "LLMs & RAG",
    keywords: ["generative ai", "genai", "llm", "llms", "prompt engineering", "rag", "langchain"],
  },
  {
    id: "data-science",
    name: "Data Science",
    stack: "Python • Statistics • Data Analysis • Viz",
    icon: BarChart3,
    description: "Statistical modeling, exploratory data analysis, data visualization, feature engineering, and predictive pipelines.",
    accentColor: "#059669",
    bgColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    tag: "Data & Stats",
    keywords: ["data science", "data analysis", "statistics", "pandas", "numpy", "visualization"],
  },
  {
    id: "dsa",
    name: "Data Structures & Algorithms",
    stack: "Arrays • Trees • Graphs • DP • Complexity",
    icon: Binary,
    description: "Core algorithm design, problem-solving strategies, graph traversals, dynamic programming, and interview prep.",
    accentColor: "#e11d48",
    bgColor: "#fff1f2",
    borderColor: "#fecdd3",
    tag: "DSA & Problem Solving",
    keywords: ["dsa", "data structures", "algorithms", "arrays", "trees", "graphs", "dynamic programming"],
  },
  {
    id: "cloud-computing",
    name: "Cloud Computing",
    stack: "AWS • Azure • Architecture • Deployment",
    icon: Cloud,
    description: "Cloud infrastructure, serverless architectures, multi-region deployments, storage, and cloud governance.",
    accentColor: "#0891b2",
    bgColor: "#ecfeff",
    borderColor: "#a5f3fc",
    tag: "Cloud & Infra",
    keywords: ["cloud", "aws", "azure", "cloud computing", "serverless", "gcp"],
  },
  {
    id: "devops",
    name: "DevOps",
    stack: "Docker • CI/CD • Git • Monitoring",
    icon: GitBranch,
    description: "Automated build and test pipelines, containerization, deployment workflows, and infrastructure reliability.",
    accentColor: "#475569",
    bgColor: "#f8fafc",
    borderColor: "#cbd5e1",
    tag: "CI/CD & Containers",
    keywords: ["devops", "docker", "kubernetes", "ci/cd", "monitoring", "terraform"],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    stack: "Web Security • Auth • Network Security",
    icon: ShieldCheck,
    description: "Threat modeling, authentication protocols, penetration testing, OWASP standards, and secure coding practices.",
    accentColor: "#be123c",
    bgColor: "#fff1f2",
    borderColor: "#fecdd3",
    tag: "SecOps & Defense",
    keywords: ["security", "cybersecurity", "web security", "auth", "network security", "infosec"],
  },
  {
    id: "database-technologies",
    name: "Database",
    stack: "MongoDB • MySQL • PostgreSQL • DB Design",
    icon: Database,
    description: "Relational and document database design, query optimization, indexing strategies, transactions, and scaling.",
    feedDescription: "Explore relational and document databases, SQL optimization, indexing strategies, and database architecture.",
    accentColor: "#b45309",
    bgColor: "#fef3c7",
    borderColor: "#fde68a",
    tag: "Data & Storage",
    keywords: ["database", "sql", "postgresql", "mysql", "mongodb", "redis", "db design"],
    aliases: ["Database", "Database Technologies", "Database & SQL", "SQL"],
  },
  {
    id: "mobile-development",
    name: "Mobile Development",
    stack: "Flutter • Android • React Native • iOS",
    icon: Smartphone,
    description: "Cross-platform and native mobile app engineering, responsive UI, app stores, and native device APIs.",
    accentColor: "#3b82f6",
    bgColor: "#eff6ff",
    borderColor: "#bfdbfe",
    tag: "Mobile Apps",
    keywords: ["mobile", "flutter", "react native", "android", "ios", "mobile development"],
  },
  {
    id: "computer-networks",
    name: "Computer Networks",
    stack: "TCP/IP • HTTP • DNS • Fundamentals",
    icon: Network,
    description: "Protocol architectures, socket programming, network layer routing, TLS handshakes, and WebSockets.",
    accentColor: "#0284c7",
    bgColor: "#f0f9ff",
    borderColor: "#bae6fd",
    tag: "Protocols & Web",
    keywords: ["network", "networks", "tcp/ip", "http", "dns", "websockets", "computer networks"],
  },
  {
    id: "software-engineering",
    name: "Software Engineering",
    stack: "SDLC • Architecture • Testing • Clean Code",
    icon: Cpu,
    description: "System design principles, clean architecture, automated testing, code reviews, and software craftmanship.",
    accentColor: "#1d4ed8",
    bgColor: "#eff6ff",
    borderColor: "#bfdbfe",
    tag: "Architecture & QA",
    keywords: ["software engineering", "sdlc", "architecture", "testing", "clean code", "system design"],
  },
  {
    id: "git-github",
    name: "Git & GitHub",
    stack: "Version Control • Branching • Collaboration",
    icon: GitPullRequest,
    description: "Git branching strategies, pull requests, merge conflict resolution, open source workflows, and GitHub Actions.",
    accentColor: "#ea580c",
    bgColor: "#fff7ed",
    borderColor: "#fed7aa",
    tag: "VCS & Workflows",
    keywords: ["git", "github", "version control", "branching", "collaboration", "pull requests"],
  },
];

export const CONTENT_TYPES = [
  "All Resources",
  "Technical Roadmap",
  "Guide & Tutorial",
  "Interview Preparation",
  "Architecture & System",
  "Project Experience",
  "Technical Article",
];

export const getDomainById = (id) => {
  if (!id) return null;
  return DOMAINS.find((d) => d.id.toLowerCase() === id.toLowerCase());
};

export const getDomainByName = (name) => {
  if (!name) return null;
  const n = name.trim().toLowerCase();
  return DOMAINS.find(
    (d) =>
      d.name.toLowerCase() === n ||
      d.id.toLowerCase() === n ||
      (d.aliases && d.aliases.some((a) => a.toLowerCase() === n))
  );
};

export const getDomainMeta = (identifier) => {
  if (!identifier || identifier === "All") return null;
  return getDomainByName(identifier);
};

